server:
  port: 8080 # El puerto principal por donde entrarán todos los clientes

spring:
  application:
    name: api-gateway # El nombre con el que aparecerá en Eureka
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Permite enrutar automáticamente usando los nombres de Eureka
          lower-case-service-id: true
      routes:
        - id: ms-catalogo
          uri: lb://ms-catalogo
          predicates:
            - Path=/api/catalogo/**
        - id: ms-stock
          uri: lb://ms-stock
          predicates:
            - Path=/api/stock/**
        - id: ms-clientes
          uri: lb://ms-clientes
          predicates:
            - Path=/api/clientes/**
        - id: ms-reservas
          uri: lb://ms-reservas
          predicates:
            - Path=/api/reservas/**
        - id: ms-cocina
          uri: lb://ms-cocina
          predicates:
            - Path=/api/cocina/**



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Aquí le indicamos dónde está Eureka
