server:
  port: 8081 # Le damos un puerto propio, distinto al Gateway (8080) y Eureka (8761)

spring:
  application:
    name: ms-catalogo # Así lo buscará el Gateway y los demás microservicios
  
  # Configuración de la Base de Datos (Ejemplo con MySQL)
  datasource:
    # createDatabaseIfNotExist=true hará que Spring cree db_catalogo automáticamente
    url: jdbc:mysql://localhost:3306/db_catalogo?createDatabaseIfNotExist=true
    username: root
    password: "" # Pon aquí tu contraseña de MySQL -- En XAMPP va vacío
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update # Crea y actualiza las tablas automáticamente basándose en tu código Java
    show-sql: true # Muestra por consola las consultas SQL que hace por detrás (muy útil para la defensa)

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
